<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="wsdlWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/wsdlWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/wsdlWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="urn:WashOutUser" xmlns:ns1="urn:WashOutBank">
    <import location="http://ec2-34-204-168-203.compute-1.amazonaws.com:3010/wsusers/wsdl" namespace="urn:WashOutUser"/>
    <import location="http://ec2-34-204-168-203.compute-1.amazonaws.com:3000/wsbanks/wsdl" namespace="urn:WashOutBank"/>
    <plnk:partnerLinkType name="wsusers_portLinkType">
        <plnk:role name="wsusers_portRole" portType="ns:wsusers_port"/>
    </plnk:partnerLinkType>
    <plnk:partnerLinkType name="wsbanks_portLinkType">
        <plnk:role name="wsbanks_portRole" portType="ns1:wsbanks_port"/>
    </plnk:partnerLinkType>
</definitions>
